const POSTMARK_API_KEY = process.env.POSTMARK_API_KEY;
const SUPABASE_URL = 'https://szifhqmrddmdkgschkkw.supabase.co';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

exports.handler = async function(event, context) {
    const headers = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type, Authorization',
        'Content-Type': 'application/json'
    };
    if (event.httpMethod === 'OPTIONS') return { statusCode: 200, headers, body: '' };
    if (event.httpMethod !== 'POST') return { statusCode: 405, headers, body: JSON.stringify({ error: 'Method not allowed' }) };

    try {
        // Auth check — require valid JWT
        const authHeader = event.headers.authorization || event.headers.Authorization || '';
        const jwt = authHeader.replace('Bearer ', '');
        if (!jwt) return { statusCode: 401, headers, body: JSON.stringify({ error: 'Not authenticated' }) };

        // Verify JWT via Supabase
        const userRes = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
            headers: { 'Authorization': `Bearer ${jwt}`, 'apikey': SUPABASE_ANON_KEY }
        });
        if (!userRes.ok) return { statusCode: 401, headers, body: JSON.stringify({ error: 'Invalid session' }) };
        const { id: inviterId } = await userRes.json();

        const { email, first_name, last_name, org_id } = JSON.parse(event.body || '{}');
        if (!email || !org_id) return { statusCode: 400, headers, body: JSON.stringify({ error: 'email and org_id required' }) };

        // Fetch org (verify caller is owner)
        const orgRes = await fetch(`${SUPABASE_URL}/rest/v1/organizations?id=eq.${org_id}&select=*`, {
            headers: { 'Authorization': `Bearer ${SUPABASE_SERVICE_KEY}`, 'apikey': SUPABASE_SERVICE_KEY }
        });
        const orgs = await orgRes.json();
        const org = orgs?.[0];
        if (!org) return { statusCode: 404, headers, body: JSON.stringify({ error: 'Organization not found' }) };
        if (org.owner_user_id !== inviterId) return { statusCode: 403, headers, body: JSON.stringify({ error: 'Only the org owner can send invites' }) };

        // Check seat limit
        const membersRes = await fetch(`${SUPABASE_URL}/rest/v1/org_members?org_id=eq.${org_id}&is_active=eq.true&select=id`, {
            headers: { 'Authorization': `Bearer ${SUPABASE_SERVICE_KEY}`, 'apikey': SUPABASE_SERVICE_KEY }
        });
        const members = await membersRes.json();
        if (members.length >= org.seat_limit) {
            return { statusCode: 400, headers, body: JSON.stringify({ error: `Seat limit reached (${org.seat_limit} seats). Upgrade your plan to invite more estimators.` }) };
        }

        // Create pending org_members row (invite_token auto-generated by DB default)
        const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/org_members`, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${SUPABASE_SERVICE_KEY}`,
                'apikey': SUPABASE_SERVICE_KEY,
                'Content-Type': 'application/json',
                'Prefer': 'return=representation'
            },
            body: JSON.stringify({
                org_id,
                invited_by: inviterId,
                invite_email: email,
                display_name: [first_name, last_name].filter(Boolean).join(' ') || email,
                role: 'estimator',
                is_active: true,
            })
        });
        const [newMember] = await insertRes.json();
        const invite_token = newMember?.invite_token;

        // Send invite email
        const inviteUrl = `https://app.bidintell.ai?invite=${invite_token}`;
        const firstName = first_name || email.split('@')[0];
        await fetch('https://api.postmarkapp.com/email', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', 'X-Postmark-Server-Token': POSTMARK_API_KEY },
            body: JSON.stringify({
                From: 'hello@bidintell.ai',
                To: email,
                Bcc: 'ryan@bidintell.ai',
                Subject: `You've been invited to join ${org.name} on BidIntell`,
                HtmlBody: `
                    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:520px;margin:0 auto;background:#fff;color:#111;">
                        <div style="padding:32px 0 16px;text-align:center;">
                            <span style="display:inline-block;background:#F26522;color:white;font-weight:800;font-size:15px;padding:8px 14px;border-radius:6px;">BidIntell</span>
                        </div>
                        <div style="padding:8px 32px 40px;">
                            <h2 style="font-size:22px;font-weight:700;color:#111;margin:0 0 12px;">You're invited to join ${org.name}</h2>
                            <p style="color:#555;font-size:15px;line-height:1.6;margin:0 0 28px;">Hi ${firstName}, your team has set up a BidIntell account and invited you to join. BidIntell scores bid documents so you can make faster, smarter GO/NO-GO decisions.</p>
                            <div style="text-align:center;margin:0 0 32px;">
                                <a href="${inviteUrl}" style="display:inline-block;background:#F26522;color:#fff;text-decoration:none;font-weight:700;font-size:16px;padding:14px 36px;border-radius:6px;">Accept Invitation &rarr;</a>
                            </div>
                            <p style="color:#888;font-size:13px;line-height:1.5;">If you weren't expecting this invitation, you can ignore this email.</p>
                        </div>
                        <div style="border-top:1px solid #eee;padding:16px 32px;text-align:center;">
                            <p style="font-size:12px;color:#aaa;margin:0;">BidIntell &middot; <a href="https://bidintell.ai" style="color:#aaa;">bidintell.ai</a></p>
                        </div>
                    </div>
                `,
                MessageStream: 'outbound'
            })
        });

        return { statusCode: 200, headers, body: JSON.stringify({ success: true }) };
    } catch (err) {
        console.error('invite.js error:', err);
        return { statusCode: 500, headers, body: JSON.stringify({ error: err.message }) };
    }
};
